services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 071208
      POSTGRES_DB: Learning
    volumes:
      - postgres_data:/var/lib/postgresql/data
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Learning
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 071208
    env_file:
      - .env.local
    volumes:
      - .:/app
    networks:
      - learning-network

networks:
  learning-network:
    driver: bridge

volumes:
  postgres_data: