services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - learning-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/Learning
    env_file:
      - .env.local
    networks:
      - learning-network

networks:
  learning-network:
    driver: bridge