spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Learning
    username: postgres
    password: 071208
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
    shutdown:
      enabled: true
