spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Learning
    username: postgres
    password: 071208
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:

  profiles:
    default: dev
  config:
    import: optional:file:.env.local[properties]
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
        exclude: env,beans
  endpoint:
    prometheus:
      enable: true
  metrics:
    tags:
      application: "my-app"
    enable:
      all: true
  shutdown:
    enabled: true

cloudflare:
  r2:
    bucketName: cdn-assets