spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Learning
    username: postgres
    password: 071208
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: WARN
    org.example.config: DEBUG
    org.springframework.boot.context.config: DEBUG
  file:
    name: logs/myapp.log
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
    shutdown:
      enabled: true
