spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Learning
    username: ${spring.datasource.username:postgres}
    password: ${spring.datasource.password:071208}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:

  profiles:
    default: dev
  config:
    import: optional:file:.env.local[properties]
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ${oauth.github.client-id}
            client-secret: ${oauth.github.client-secret}
            scope:
              - user
              - user:email

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
        exclude: env,beans
  endpoint:
    prometheus:
      enable: true
  metrics:
    tags:
      application: "my-app"
    enable:
      all: true
  shutdown:
    enabled: true

cloudflare:
  r2:
    bucketName: cdn-assets

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/Learning
    username: ${spring.datasource.username:postgres}
    password: ${spring.datasource.password:071208}
  redis:
    host: redis
    port: 6379

  # feature flags
  firebase:
    enabled: false
